version: 2

# Enabling Dependabot version updates @see: https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-dependabot-version-updates#enabling-dependabot-version-updates
updates:
  # GitHub Actions (action.y*ml) & Workflows (*.y*ml in .github/workflows/)
  - package-ecosystem: "github-actions"
    directories: [ "/" ]
    schedule:
      interval: "daily"

  # Maven (pom.xml)
  - package-ecosystem: "gradle"
    directories: [ "/" ]
    schedule:
      interval: "daily"
